Vagrant.configure("2") do |config|
#   config.vm.box = "bitsydarel/macOSSandBox"
  config.vm.box = "macOSSandBox"
#   config.vm.box_version = "v0.2"
  config.vm.network "private_network", type: "dhcp"
  config.vm.boot_timeout = 1800 # boot timeout is set to 30 seconds
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "flutter_stable_macOSSandbox"
    vb.gui = false
    vb.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
  end

  config.vm.provision "shell" do |script|
    script.name = "stable"
    script.path = "https://raw.githubusercontent.com/bitsydarel/flutter-ci/master/scripts/install_flutter.sh"
    script.env = {"VAGRANT_HOME" => "/Users/vagrant", "flutter_version" => "stable"}
    script.privileged = false
  end

end